# Generated by Django 5.2 on 2025-04-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_like_savedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
